### ISSUE TITLE
Concurrency problem and clash of metadata

### ISSUE THREAD

**Issue by s256** [sHorst/bw.bundle.iptables#4]
Thank you for publishing your bundle! not a lot of people seem to be using bundlewrap ;)
I'm currently struggling with some problems after cloning your bundle in my setup.

During an `bw apply` I receive
```
✘ fancy-hostname  iptables  iptable:filter  failed
│   File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/concurrency.py", line 133, in run
│     result = self._get_result()
│              ^^^^^^^^^^^^^^^^^^
│   File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/concurrency.py", line 73, in _get_result
│     raise exception
│   File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
│     result = self.fn(*self.args, **self.kwargs)
│              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/items/__init__.py", line 553, in apply
│     status_before = self.cached_status
│                     ^^^^^^^^^^^^^^^^^^
│   File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/utils/__init__.py", line 36, in cache_wrapper
│     return_value = prop(self)
│                    ^^^^^^^^^^
│   File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/items/__init__.py", line 321, in cached_status
│     return self.get_status()
│            ^^^^^^^^^^^^^^^^^
│   File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/items/__init__.py", line 800, in get_status
│     return ItemStatus(self.cached_cdict, self.cached_sdict)
│                       ^^^^^^^^^^^^^^^^^
│   File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/utils/__init__.py", line 49, in cache_wrapper
│     raise Exception("AttributeError in property, see above") from exc
│ Exception('AttributeError in property, see above')
```
if I have multiple bundles (>3) with iptables rules in metadata, with code like:
`metadata.py`
```python
@metadata_reactor
def add_iptables_rules(metadata):
    if not node.has_bundle("iptables"):
        raise DoNotRunAgain
    else:
        iptables_rules = {}
        iptables_rules += repo.libs.iptables.accept(). \
            state('NEW'). \
            tcp(). \
            dest_port('22')
        return iptables_rules
```

I'm pretty sure, that's related to the output of `bw test`:
```
✓ No reactors violated their declared keys
Traceback (most recent call last):
File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/utils/cmdline.py", line 71, in wrapper
return f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^
File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/cmdline/__init__.py", line 77, in main
pargs.func(repo, text_pargs)
File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/cmdline/test.py", line 297, in bw_test
test_metadata_conflicts(node, args['quiet'])
File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/cmdline/test.py", line 91, in test_metadata_conflicts
check_for_metadata_conflicts(node)
File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/metadata.py", line 89, in check_for_metadata_conflicts
check_for_metadata_conflicts_between_defaults_and_reactors(node)
File "/home/code/bundlewrap/.venv/lib/python3.11/site-packages/bundlewrap/metadata.py", line 136, in check_for_metadata_conflicts_between_defaults_and_reactors
raise ValueError(_(
ValueError: fancy-hostname: metadata_reactor:nginx.add_iptables_rules and metadata_reactor:postgres.add_iptables_rules are clashing over this key path: iptables/rules ([{'jump': 'ACCEPT', 'input': 'public_interface', 'state': 'NEW', 'protocol': 'tcp', 'tcp_dest_port': '80'}, {'jump': 'ACCEPT', 'input': 'public_interface', 'state': 'NEW', 'protocol': 'tcp', 'tcp_dest_port': '443'}] vs. [{'jump': 'ACCEPT', 'input': 'lo', 'state': 'NEW', 'protocol': 'tcp', 'tcp_dest_port': '5432'}])
```
While the clashing metadata is never the same if I run it more often. I'm a bit in over my head to be honest.

If you have a tip on where to look, that would be highly appreciated.

**Comment by sHorst** [comment]
hmm .. i have to look into this. .. the magic __radd__ function is adding a non dict do the metadata, maybe that is the problem. will investigate.
